import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-slate-900 to-slate-700 text-white`}
      >
        <nav className="py-4 border-b-orange-50 border-b">
          <ul className="flex gap-5 p-4">
            <li>
              <Link href={`/`}>Home</Link>
            </li>
            <li>
              <Link href={`/portal`}>Portal</Link>
            </li>
            <li>
              <Link href={`/employee`}>Employee</Link>
            </li>
            <li>
              <Link href={`/customer`}>Customer</Link>
            </li>
            <li>
              <Link href={`/vendor`}>Vendor</Link>
            </li>
            <li>
              <Link href={`/blogs`}>Blogs</Link>
            </li>
            <li>
              <Link href={`/parallel`}>Parallel</Link>
            </li>
            <li>
              <Link href={`/gallery`}>Gallery</Link>
            </li>
            <li>
              <Link href={`/data-fetching`}>Data Fetching</Link>
            </li>
          </ul>
        </nav>

        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
